# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ventana_Admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(240, 409, 391, 111))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.boton_Agregar = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.boton_Agregar.setObjectName("boton_Agregar")
        self.horizontalLayout.addWidget(self.boton_Agregar)
        self.boton_Buscar = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.boton_Buscar.setObjectName("boton_Buscar")
        self.horizontalLayout.addWidget(self.boton_Buscar)
        self.boton_Actualizar = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.boton_Actualizar.setObjectName("boton_Actualizar")
        self.horizontalLayout.addWidget(self.boton_Actualizar)
        self.tablaUsuarios = QtWidgets.QTableWidget(self.centralwidget)
        self.tablaUsuarios.setGeometry(QtCore.QRect(30, 30, 800, 350))
        self.tablaUsuarios.setObjectName("tablaUsuarios")
        self.tablaUsuarios.setColumnCount(0)
        self.tablaUsuarios.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.boton_Agregar.setText(_translate("MainWindow", "Agregar"))
        self.boton_Buscar.setText(_translate("MainWindow", "Buscar"))
        self.boton_Actualizar.setText(_translate("MainWindow", "Actualizar"))
